= Couchbase Upgrades

[abstract]
The Operator allows a managed Couchbase cluster to be upgraded.
This includes upgrading the Couchbase Server version and also related Kubernetes resources.

== Upgrading Couchbase Server

The Couchbase Server version can be xref:howto-couchbase-upgrade.adoc[upgraded] by the Operator. To upgrade a Couchbase Cluster, change the couchbasecluster.spec.image field in the cluster manifest to the version you wish to upgrade to. The Operator will then handle upgrading the pods running Couchbase Server which make up the Couchbase cluster. During an upgrade, the cluster version can also be rolled back to the previous version by reverting the image field change. The Operator will then perform the upgrade effectively in reverse, following the configured upgrade controls but for pods on the old version.

For more granular control, the upgrade process can be managed and controlled using `spec.upgrade`` in the CouchbaseCluster resource.

[source,yaml]
----
upgrade:
  upgradeProcess: SwapRebalance # <.>
  upgradeStrategy: RollingUpgrade # <.>
  rollingUpgrade: # <.>
    maxUpgradable: 1
    maxUpgradablePercent: 100%
  stabilizationPeriod: 10s # <.>
  previousVersionPodCount: 0 # <.>
  upgradeOrderType: Nodes # <.>
  upgradeOrder:
    - node-1
    - node-2
----
<.> UpgradeProcess can be one of SwapRebalance or InPlaceUpgrade, defaulting to SwapRebalance. The strategy by which SwapRebalance will create pods on the upgraded version is determined by the chosen UpgradeStrategy. InPlaceUpgrade can only be used when strategy is set to RollingUpgrade.

- During a SwapRebalance, one or more candidate pods are selected and new pods are created for each. Data is then rebalanced from the old pods before the candidate pods are deleted.

- During an InPlaceUpgrade, one or more candidate pods are selected and failed over. Those pods then have their volumes detached and then replaced with pods on the new version. Operator will then bind the existing volumes onto the new pods. This process is quicker than a rolling upgrade and pod names and network settings will be retained by the updated pod. 

<.> UpgradeStrategy determines how a SwapRebalance will create new pods, either by RollingUpgrade or ImmediateUpgrade. InPlaceUpgrades require a RollingUpgrade strategy.

- RollingUpgrade performs the upgrade operation a predetermined number of pods at a time, limiting the risk of an issue and can more easily be rolled back. A rolling upgrade requires the least network and compute overhead, so will affect the client operation less.

- ImmediateUpgrade poses greater risk and will increase resource utilization during the upgrade, however the operation itself is significantly faster. This strategy may have an undesired effect on client performance as all pods in the cluster are undergoing upgrade at the same time.

<.> StabilizationPeriod lets you control how long the Operator should wait between each upgrade cycle, allowing for a period of time where you might want to check for cluster health or service availability.

<.> PreviousVersionPodCount tells the Operator to leave a fixed number of pods running the previous version. This might be useful to allow for rollbacks or an extended StabilizationPeriod on the final pods during a cluster upgrade. Couchbase Server will not be considered upgraded until all pods in the cluster are on the new version. The Operator will also consider the cluster to be in “Mixed Mode”, which restricts some features.

<.> UpgradeOrderType gives you granular upgrade ordering controls to allow for pre-determination on the order by which the Operator will upgrade pods to the new version. UpgradeOrderType determines how we interpret UpgradeOrder. This must be one of Nodes, ServerGroups, ServerClasses or Services. The sequence given in UpgradeOrder will then be used for upgrade ordering. Anything missing from this sequence will revert to the default ordering mechanism.

[NOTE]
====
InPlaceUpgrade is a volatile process that can lead to interruptions in service. It should not be used when there are less than 2 data nodes defined or data loss may occur.
====

=== How to Upgrade a Cluster

To upgrade a cluster, you need to modify the CouchbaseCluster resource to specify the new version of Couchbase Server that you want to upgrade to. This is done by updating the `spec.image` field in the CouchbaseCluster manifest to the new version.

For example, if you were upgrading from Couchbase Server 7.6.7 to 8.0.0 then the manifest resource needs to be updated as follows:

[source,yaml]
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: my-couchbase-cluster
spec:
  image: couchbase/server:8.0.0
---

During an upgrade or while the cluster is in Mixed Mode (via PreviousVersionPodCount), bucket storage backend migrations and changes to sidecar containers like cloud native gateway and fluent bit will be disabled.

Refer to the Couchbase Server upgrade documentation for information on permitted upgrade paths.

[NOTE]
====
Modifying the Couchbase Server version while an upgrade is in progress is permitted only if the version you are changing to is a roll-back to the previous version.
====

=== Rollback

The Operator provides the capability to rollback upgrades in progress. A rollback is only allowed while there are pods in the cluster still running the previous version. This should only occur while an upgrade is in progress or the cluster is in mixed mode. Once a cluster is fully upgraded to the new version, it can no longer be rolled back. A rollback simply consists of replacing the newly created pods with ones running the previous version. Like an upgrade, the strategy, process and ordering of a rollback is still determined via the `spec.upgrade`` configuration.

==== How to Rollback a Cluster

To initiate a rollback, you need to modify the CouchbaseCluster manifest to specify the previous version of Couchbase Server that was running before the upgrade started. This is done by updating the `spec.image`` field.

For example, if you were upgrading from Couchbase Server 7.6.7 to 8.0.0 and encountered issues that require a rollback, you can change the version back to 7.6.7 by updating the manifest as follows:

[source,yaml]
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: my-couchbase-cluster
spec:
  image: couchbase/server:7.6.7
---

=== Controlled Upgrades

The Operator provides the capability to control the upgrade process using the fields in couchbasecluster.spec.upgrade. For example, it’s possible to upgrade the pods depending on which availability region they are running in, or alternatively which Couchbase Server services they are running. As an administrator you might want to upgrade pods that run the data service before the query service, or perhaps a specific pod with a given name should be upgraded before another.

[NOTE]
====
For as long as there are pods running two versions in a cluster, the Operator will consider the cluster to be in “Mixed Mode” and restrict some features (bucket migration, sidecar changes). Ideally the time spent in this mode is kept to a minimum.
====

=== Upgrading Pods

Pods in Kubernetes are immutable. If a CouchbaseCluster manifest is modified in a way that requires a replacement of any underlying pods, the Operator will create these new pods in the same way an upgrade occurs to replace a pod on an old version. In fact, upgrading Couchbase Server is just a subset of modifying any other pod specification parameter.

The Operator builds pod specifications depending on the manifest and compares those to the existing pods in the cluster. Candidates are selected from any where the specifications differ. The Operator therefore can perform the following tasks:

* Modification of scheduling constraints
* Modification of environment variables
* Modification of memory constraints
* Modification of Couchbase services
* Enabling and disabling of TLS
* Enabling and disabling of persistent storage

This mechanism allows a cluster to be used from evaluation right up to production, with features enabled as they are required, without service disruption.

=== Upgrading Persistent Volumes

The Operator supports modification to volumes using a similar mechanism to upgrading pods. Changes to a manifest that require updates to persistent volumes will result in a pod upgrade in order to satisfy the request. Persistent volumes that are already in use can be optionally expanded in-place using `couchbasecluster.spec.enableOnlineVolumeExpansion` without needing to perform an upgrade on the pod, as long as the storage class and Kubernetes cluster support persistent volume resizing.

During an InPlaceUpgrade, any PVC's will be updated to include the updated image and Couchbase Server versions. The size of the PVC and data within will not be edited unless modification is also required to match the desired cluster manifest.