= Configure Client Certificate Authentication

[abstract]
How to configure Couchbase Server and the Operator to use client certificate based authentication.

By default a Couchbase Server deployment uses basic authentication, commonly known as username and password.
Basic authentication may be used over a plain text network communication where a malicious party can see the password.
Basic authentication may also be used over a server-side TLS protected network connection which encrypts the password and prevents a malicious party from acquiring it.

Couchbase Server also supports a mode of authentication using client certificates.
It uses the same technology that a client uses to assert the validity of a server certificate, but the server validates the client as well.
This is known as mutual TLS (mTLS).
Couchbase server does not support basic authentication over mTLS, instead requiring a username to be encoded into the client certificate.
This page documents configuration of mTLS.

== Creating Secrets

Secrets are specified in the `CouchbaseCluster` resource, therefore they may have any name you choose. The format of individual secrets is discussed below.

Please see the xref:tutorial-tls.adoc[TLS certificate tutorial] for a simple guide to creating TLS certificates.

=== Server Secret

Server secrets need to be mounted as a volume within the Couchbase Server pod with specific names. The certificate chain must be named `tls.crt` and the private key `tls.key`.

[source,console]
----
$ kubectl create secret generic couchbase-server-tls \
  --from-file example/tls/certs/tls.crt \
  --from-file example/tls/certs/tls.key \
  --from-file example/tls/certs/ca.crt
----

=== Operator Secret

The Operator client secrets are read directly from the API. It expects only a single value to be present; `ca.crt` is the top-level CA which is used to authenticate all TLS server certificate chains.
When using client certificate authentication you will also need to specify the client certificate chain and key pair with the keys `tls.crt` and `tls.key` respectively:

[source,console]
----
$ kubectl create secret generic couchbase-operator-tls \
  --from-file example/tls/certs/tls.crt \
  --from-file example/tls/certs/tls.key
----

== Couchbase Cluster Configuration

TLS certificate configuration is done in the networking section of the `CouchbaseCluster` resource.

[source,yaml]
----
apiVersion: couchbase/v2
kind: CouchbaseCluster
spec:
  security:
    adminSecret: my-admin-secret
  networking:
    tls:
      secretSource:
        serverSecretName: couchbase-server-tls # <.>
        clientSecretName: couchbase-operator-tls # <.>
      clientCertificatePolicy: mandatory # <.>
      clientCertificatePaths: # <.>
      - path: subject.cn
      - path: san.email
        delimiter: @
----

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-tls-secretsource-serversecretname[`couchbaseclusters.spec.networking.tls.secretSource.serverSecretName`] defines a secret that will be mounted to all Couchbase Server pods.
It contains the server wildcard certificate and it's private key.
As the private key is securely mounted to the pod by Kubernetes it is never exposed over the network.

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-tls-secretsource-clientsecretname[`couchbaseclusters.spec.networking.tls.secretSource.clientSecretName`] defines a secret containing client related certificates.
The client certificate contains a subject common name e.g. `Administrator`.
The administrator user `Administrator` is configured by the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-security-adminsecret[`couchbaseclusters.spec.security.adminSecret`].

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-tls-clientcertificatepolicy[`couchbaseclusters.spec.networking.tls.clientCertificatePolicy`] is set to mandatory meaning all clients will need to provide a valid client certificate in order to authenticate against the cluster.

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-tls-clientcertificatepaths[`couchbaseclusters.spec.networking.tls.clientCertificatePaths`] defines a path that is able to correctly parse and extract the Operator's `Administrator` use from the client certificate.
In this example all we need to specify is that the user name is explicitly encoded in the certificate's subject common name.
This covers the base requirements in order for the Operator to be able to connect to the cluster.
+
In a more realistic setup users will likely be identified by an email address.
In this illustration it is encoded in a subject alternative name (SAN).
When Couchbase Server looks at a client certificate it will not find a valid user using the first path (but it would match for our `Administrator` user).
It then proceeds down the list of paths in order trying to extract a valid username.
If the client certificate contained a SAN `EMAIL:jane.doe@example.com`, then it would resolve to `jane.doe` with our second path rule.
If `jane.doe` matched a local or LDAP user then they would be granted permission to access the Couchbase Server instance.

== Setting Up Mandatory mTLS

Setting `clientCertificatePolicy` to `mandatory` requires every client to present a valid certificate, including the Couchbase Server nodes themselves.
Applying it before all of the certificates are in place can leave the cluster unreachable.
Introduce it in stages instead, confirming the cluster is healthy before moving on to the next stage.

The procedure below was performed on Operator 2.9.3 with Couchbase Server 8.0.2, using cert-manager to issue the certificates.

=== Certificates

A single certificate authority signs three certificates:

[cols="1,3"]
|===
| Certificate | Purpose

| Server
| Presented by each Couchbase Server pod.
Held in the secret named by `secretSource.serverSecretName`.

| Operator client
| Presented by the Operator when it connects to the cluster.
Held in the secret named by `secretSource.clientSecretName`.

| Internal client
| Presented by a Couchbase Server node when it connects to another node as a client.
Held in the secret named by the `nodeClientSecretName` annotation, described in Step 3.
|===

The internal client certificate needs a subject alternative name of type email, the `digital signature`, `key encipherment` and `client auth` key usages, and a common name that does not match any RBAC user.

=== Step 1: Server TLS Only

Start with a server certificate and no client certificates.
Clients continue to authenticate with a password at this stage.

[source,yaml]
----
spec:
  networking:
    tls:
      nodeToNodeEncryption: All
      tlsMinimumVersion: TLS1.2
      validateBareHostnames: true
      allowPlainTextCertReload: false
      secretSource:
        serverSecretName: couchbase-server-tls
----

=== Step 2: Add Client Certificates with `enable`

Add the Operator client certificate and set `clientCertificatePolicy` to `enable`.
Clients may now authenticate with a certificate, and a password still works, so a certificate that is misconfigured does not lock you out of the cluster.

[source,yaml]
----
spec:
  networking:
    tls:
      clientCertificatePolicy: enable
      clientCertificatePaths:
      - path: subject.cn
        prefix: example.gcp.nonprod.
      - path: subject.cn
        prefix: example.aws.nonprod.
      nodeToNodeEncryption: All
      tlsMinimumVersion: TLS1.2
      validateBareHostnames: true
      allowPlainTextCertReload: false
      secretSource:
        serverSecretName: couchbase-server-tls
        clientSecretName: couchbase-operator-tls
----

=== Step 3: Install the Internal Client Certificate

Name the internal client secret in an annotation on the `CouchbaseCluster` resource.
The `tls` section is unchanged from Step 2, and the policy stays at `enable`.

[source,yaml]
----
metadata:
  annotations:
    cao.couchbase.com/networking.tls.secretSource.nodeClientSecretName: couchbase-internal-client-tls
----

The Operator loads the internal client certificate onto every Couchbase Server node.

=== Step 4: Set the Policy to `mandatory`

With all three certificates in place, change `clientCertificatePolicy` from `enable` to `mandatory`.
Nothing else needs to change.

[source,yaml]
----
spec:
  networking:
    tls:
      clientCertificatePolicy: mandatory
----
