= Annotation Documentation

[abstract]
Couchbase Operator uses special annotations to configure specific resources.

== Bucket Backend Configuration
=== Managed Buckets
==== `cao.couchbase.com/buckets.defaultStorageBackend`
Used to configure the default storage backend for managed CouchbaseBucket.
Changing the storage backend of a pre-existing bucket is only supported on Couchbase Server version 7.6.0
Defaults to `couchstore`, accepts either `couchstore` or `magma`. 

=== Unmanaged Buckets
==== `cao.couchbase.com/buckets.targetUnmanagedBucketStorageBackend`
Used to force a storage backend on all buckets in a Couchbase Cluster. This configuration only takes action if bucket management is disabled
When configured the Couchbase Operator will attempt to force all buckets in a cluster to a particular storage backend.
This config is only used with Couchbase Server 7.6.0.
Accepts either `couchstore` or `magma`.

=== Bucket Migrations

==== `cao.couchbase.com/buckets.enableBucketMigrationRoutines`
By default, bucket storage backend migrations are not enabled as they will result in a swap-rebalance of every effected couchbase node. This means changing the bucket storage backend will be prevented unless this annotation is set to "true".
Accepts either `true` or `false`.

==== `cao.couchbase.com/buckets.maxConcurrentPodSwaps`
Used to change the number of pods affected by a bucket storage backend migration. By default, only one pod will be migrated at a time. This field must be a number greater than 0.

== Sample buckets
==== `cao.couchbase.com/sampleBucket`
SampleBucket indicates whether the bucket should be treated as a sample bucket.
If set to "true", the bucket name will define the sample bucket used and the bucket will be created with the sample bucket configuration, not the CRD specification.
SampleBuckets have a memory quota of 200Mi and a couchstore storage backend.
If this annotation is changed to false or removed, the bucket will then be updated with the CRD specification.
This annotation cannot be added to an existing bucket and should not be used for production clusters.

== Cluster Scheduling
=== Rescheduling To Different Server Groups On Failed Scheduling
==== `cao.couchbase.com/rescheduleDifferentServerGroup`
Used to allow Couchbase Operator to attempt to reschedule a pod to a different server group if the pod fails to schedule.
When not set, Couchbase Operator performs full server group rebalancing calculations for all pods (including unschedulable ones) to ensure the cluster remains balanced, and will retry scheduling without tracking or avoiding server groups that previously failed to schedule pods.
With this annotation set to `true` on a cluster, the operator only reschedules pods from unschedulable server groups (those removed from the cluster specification). When a pod fails to schedule on a server group multiple times, the operator tracks the failure and attempts to schedule the pod on a different server group (with the next least possible size), helping to balance the cluster.
This is a best effort mechanism. If multiple server groups fail to schedule the pod, the operator will randomly select from the available server groups defined in the server class specification.
Accepts either `true` or `false`.

=== Server Group Shuffling
==== `cao.couchbase.com/shuffleServerGroups`
Used to allow Couchbase Operator to shuffle the order that pods are scheduled to defined server groups.
By default Couchbase Operator will schedule pods to server groups in lexical order.
The shuffling is pseudo-random and is based on the cluster name and namespace, so the same cluster/namespace combination will always shuffle the server groups in the same order.
Accepts either `true` or `false`.

== Pod Rescheduling
=== Individual Pod Rescheduling
==== `cao.couchbase.com/reschedule`
Used to force a pod to be rescheduled for node maintenance purposes. When this annotation is applied to a Couchbase pod with the value `true`, the operator will detect it and reschedule the pod. The pod will either be Swap Rebalanced or go through an InPlaceUpgrade depending on xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-upgradeprocess[`couchbaseclusters.spec.upgradeProcess`].

This annotation is intended for scenarios such as Kubernetes node maintenance, cordoning, or draining operations. It is not designed for schedule balancing across server groups - server group changes during upgrades are automatically handled by the operator.
Accepts either `true` or `false`.

== Host Network 
=== Improved Host Network Support
==== `cao.couchbase.com/networking.improvedHostNetwork`
Used to enable improved host network support. This annotation is used to enable improved host network support for Couchbase Server pods.
When enabled on a cluster the operator will skip SAN validation and will add the underlying Kubernetes hostname a pod is running on to the alternate addresses list. 

==== `cao.couchbase.com/networking.initPodsWithNodeHostname`
Used to set the hostname of the pod to the name of the node it is running on. 
The annotation `cao.couchbase.com/networking.improvedHostNetwork` must also be set to `true` in order for the annotation to take effect.
When set to true, the pods will be initialised with the node name as the hostname of the pod without an alternate address.

== Cloud Native Gateway
=== OTLP Endpoint
==== `cao.couchbase.com/networking.cloudNativeGateway.otlp.endpoint`

Use this annotation to set a custom OTLP endpoint for the Cloud Native Gateway.
Apply the annotation to the cluster with a string value such as `https://otel:1234`.
The value is passed directly to the Cloud Native Gateway container.

== Backup
=== Additional Args
==== `cao.couchbase.com/full.additionalArgs`

Use this annotation to set additional arguments for `cbbackupmgr` in full backup jobs.
Provide a string that includes any values supported by xref:server:backup-restore/cbbackupmgr-backup.html[`cbbackupmgr`].

==== `cao.couchbase.com/incremental.additionalArgs`

Use this annotation to set additional arguments for `cbbackupmgr` in incremental backup jobs.
Provide a string that includes any values supported by xref:server:backup-restore/cbbackupmgr-backup.html[`cbbackupmgr`].

==== `cao.couchbase.com/merge.additionalArgs`

Use this annotation to set additional arguments for `cbbackupmgr` in merge backup jobs.
Provide a string that includes any values supported by xref:server:backup-restore/cbbackupmgr-backup.html[`cbbackupmgr`].

=== Additional Operator Backup Args
==== `cao.couchbase.com/additionalOperatorBackupArgs`

Use this annotation to set additional arguments for the backup container that are not used by `cbbackupmgr`, for example, `--force-delete-lockfile`.
Provide a string value with the flags to set.