[#release-290]
== Release 2.9.0 (November 2025)

Couchbase Operator 2.9.0 was released in November 2025.
This maintenance release contains fixes to issues.

[#fixed-issues-v290]
== Fixed Issues


*https://jira.issues.couchbase.com/browse/K8S-3258/[K8S-3258]*::

Added a new `logging.configNameReleasePrefix` boolean to the helm chart.
This defaults to false, but setting it to true will prefix the fluent-bit config with the release name.
Setting this to true for existing clusters will trigger recreation of all pods so should only really be used for new clusters.

*https://jira.issues.couchbase.com/browse/K8S-4091/[K8S-4091]*::

Updated the `spec.networking.addressFamily` field to accept `IPv4Only`, `IPv4Priority`, `IPv6Only` and `IPv6Priority`.
The current `IPv4/IPv6` values will have the `Ipv4/6Only` functionality.
I.e.
customers that have set the fields will not see any change.

+
These should be considered deprecated and will be removed in a future release.
 +
The priority/only choice determines whether `addressFamilyOnly` is true or false.

*https://jira.issues.couchbase.com/browse/K8S-4097/[K8S-4097]*::

The MirWatchdog is an out-of-band check that allows for additional alerting to be in place in the unlikely scenario that an Operator is unable to reconcile a cluster due to reasons outside of its controls/capabilities and which therefore require manual intervention by a user to resolve.
Scenarios include but are not limited to, tls expiration, couchbase authentication errors and loss of quorum.
By default this is disabled, but can be enabled and configured using the `mirWatchdog` field in the couchbase cluster CRD.
If the cluster enters this condition, it will:
+
* Set the cluster_manual_intervention gauge metric to 1
* Add (where possible) the `ManualInterventionRequired` condition to the cluster, with a message detailing the reason for entering the MIR state.
* Raise a `ManualInterventionRequired` Kubernetes event, with the event message set to the reason for entering manual intervention
* Optionally, reconciliation will be skipped until the manual intervention required state has been resolved, i.e.
the issue that put the cluster into that condition has been fixed.

*https://jira.issues.couchbase.com/browse/K8S-4144/[K8S-4144]*::

In prior versions of Couchbase Operator, the metrics port annotation (`prometheus.io/port`) was set to 8091, even if TLS was enabled.
 It will now correctly set to 18091.

*https://jira.issues.couchbase.com/browse/K8S-4161/[K8S-4161]*::

Operator 2.9.0 now allows you to set `spec.cluster.analytics.numReplicas`.
This feature is only supported for couchbase server versions 7.6+.

*https://jira.issues.couchbase.com/browse/K8S-4270/[K8S-4270]*::

Potentially where we use `kubectl apply` for CRDS, we add a note that this error is possible in 2.9+, and to add `--server-side` to the `kubectl apply` command.

*https://jira.issues.couchbase.com/browse/K8S-4286/[K8S-4286]*::

In the latest build,
the mirWatchdog feature is now set to off by default.
The sequence has been adjusted to move the skip function after the validationRunner,
and changes have been included in the CRD.
Additionally,
the system now skips the DAC during status changes.
These updates aim to streamline operations and improve efficiency.
// Generated by [chatgpt:gpt-4o]



