= Release Notes for Couchbase Kubernetes Operator {operator-version-minor}
include::partial$constants.adoc[]

Autonomous Operator {operator-version-minor} introduces our new Cluster Migration functionality well as a number of other improvements and minor fixes.

Take a look at the xref:whats-new.adoc[What's New] page for a list of new features and improvements that are available in this release.

== Installation

For installation instructions, refer to:

* xref:install-kubernetes.adoc[]
* xref:install-openshift.adoc[]

== Upgrading to Kubernetes Operator {operator-version-minor}

The necessary steps needed to upgrade to this release depend on which version of the Kubernetes Operator you are upgrading from.

=== Upgrading from 1.x, 2.0, or 2.1

There is no direct upgrade path from versions prior to 2.2.0.
To upgrade from a 1.x, 2.0.x, or 2.1.x release, you must first upgrade to 2.4.x, paying particular attention to supported Kubernetes platforms and Couchbase Server versions.
See xref:2.4@operator::howto-operator-upgrade.adoc[Couchbase Operator 2.4 upgrade steps] if upgrading from a pre-2.2 release.

include::partial$couchbase-operator-release-notes-2.9.0.adoc[]
For further information read the xref:concept-upgrade.adoc[Couchbase Upgrade] concepts page.

== Previous Release Notes

* xref:2.8@operator::release-notes.adoc[Couchbase Kubernetes Operator 2.8 Release Notes]


== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]