[#whats-new-290]
== What's New in 2.9.0 (December 2025)

Couchbase Operator 2.9.0 was released in December 2025.
New features and improvements are described below.

== New Features







[#dlist-whats-new-290-]
=== Operator

*https://jira.issues.couchbase.com/browse/K8S-3917/[K8S-3917]*::

You can now specify `overheadMemory` for autoResourceAllocation to specify a static amount of overhead.

*https://jira.issues.couchbase.com/browse/K8S-4013/[K8S-4013]*::

It is now possible to disable DNS resolution verification when creating pods, prior to activating them within the cluster.

*https://jira.issues.couchbase.com/browse/K8S-4028/[K8S-4028]*::

Added an upgrade stanza to the CouchbaseCluster resource to give users more control during upgrades.

*https://jira.issues.couchbase.com/browse/K8S-4097/[K8S-4097]*::

The MirWatchdog is an out-of-band check that allows for additional alerting to be in place in the unlikely scenario that an Operator is unable to reconcile a cluster due to reasons outside of its controls/capabilities and which therefore require manual intervention by a user to resolve. Scenarios include but are not limited to, tls expiration, couchbase authentication errors and loss of quorum.
By default this is disabled, but can be enabled and configured using the `mirWatchdog` field in the couchbase cluster CRD. If the cluster enters this condition, it will:
+
* Set the cluster_manual_intervention gauge metric to 1
* Add (where possible) the `ManualInterventionRequired` condition to the cluster, with a message detailing the reason for entering the MIR state.
* Raise a `ManualInterventionRequired` Kubernetes event, with the event message set to the reason for entering manual intervention
* Optionally, reconciliation will be skipped until the manual intervention required state has been resolved, i.e. the issue that put the cluster into that condition has been fixed.


