
[#fixed-issues-v280]
=== Fixed Issues


*https://jira.issues.couchbase.com/browse/K8S-3558[K8S-3558^]*::

Couchbase Autonomous Operator commences an In-place Upgrade when the cluster is under-resourced.

*https://jira.issues.couchbase.com/browse/K8S-3579[K8S-3579^]*::

Couchbase Autonomous Operator tries to change invalid bucket configurations in a loop.

*https://jira.issues.couchbase.com/browse/K8S-3591[K8S-3591^]*::

Couchbase Autonomous Operator crashes if Incremental Backup is missing schedule.

*https://jira.issues.couchbase.com/browse/K8S-3596[K8S-3596^]*::

Crash in Operator due to invalid memory access.

*https://jira.issues.couchbase.com/browse/K8S-3605[K8S-3605^]*::

Upgrade Swap Rebalance is retried with different parameters on Operator Pod deletion.

*https://jira.issues.couchbase.com/browse/K8S-3609[K8S-3609^]*::

 Hibernation fails to bring back any Pod with error extracting image version.

*https://jira.issues.couchbase.com/browse/K8S-3621[K8S-3621^]*::

Shadowed Secret did not get updated.

*https://jira.issues.couchbase.com/browse/K8S-3632[K8S-3632^]*::

Unable to set -1 for Collection-level `maxTTL`.

*https://jira.issues.couchbase.com/browse/K8S-3639[K8S-3639^]*::

Operator loses track of pending Pods when an Eviction of the Operator Pod occurs.

*https://jira.issues.couchbase.com/browse/K8S-3641[K8S-3641^]*::

 Crash in `handleVolumeExpansion` if `enableOnlineVolumeExpansion` is True but no Volume Mounts configured.

*https://jira.issues.couchbase.com/browse/K8S-3655[K8S-3655^]*::

 Clear Upgrade condition if the Operator is not performing an upgrade.

*https://jira.issues.couchbase.com/browse/K8S-3659[K8S-3659^]*::

 When scaling down, Cluster does not maintain balance across Server Groups.

*https://jira.issues.couchbase.com/browse/K8S-3696[K8S-3696^]*::

 DAC prevents configuration of multiple XDCR Replications of same Buckets to different remote Clusters.

*https://jira.issues.couchbase.com/browse/K8S-3772[K8S-3772^]*::

Self-Certification: Artifacts PVC should use `--storage-class` parameter when creating the Certification Pod.

*https://jira.issues.couchbase.com/browse/K8S-3788[K8S-3788^]*::

Operator container crashes when there is a managed Scope/Collection Group added for the Ephemeral Bucket.

|===


[#known-issues-v280]
=== Known Issues

[#table-known-issues-v280,cols="25,66"]
|===
| Issue | Description

*https://jira.issues.couchbase.com/browse/K8S-3617[K8S-3617^]*::

It's not possible to set xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-cluster-indexer-redistributeindexes[`couchbaseclusters.spec.cluster.indexer.redistributeIndexes`] from True to False during a reconciliation.

*https://jira.issues.couchbase.com/browse/K8S-3908[K8S-3908^]*::

Metric `couchbase_operator_memory_under_management_bytes` is incorrectly showing 0.

*https://jira.issues.couchbase.com/browse/K8S-3909[K8S-3909^]*::

Metric `couchbase_operator_cpu_under_management` is incorrectly showing 0.

*https://jira.issues.couchbase.com/browse/K8S-3910[K8S-3910^]*::

Operator tries to migrate storage backend of buckets even before couchbase cluster is in 7.6.0+.

|===
