[#release-281]
== Release 2.8.1 (June 2025)

Couchbase Operator 2.8.1 was released in June 2025.
This maintenance release contains fixes to issues.

[#fixed-issues-v281]
== Fixed Issues


[#table-fixed-issues-v281,cols="25,66"]


*https://jira.issues.couchbase.com/browse/K8S-3793/[K8S-3793]*::

Fixed a bug in Local Persistent Volume comparison logic that previously triggered unnecessary pod rebalancing when comparing existing and desired states, despite no actual differences being detected.

*https://jira.issues.couchbase.com/browse/K8S-3840/[K8S-3840]*::

Due to ephemeral volumes removing the staging directory, backups will fail if the defaultRecoveryMethod is set to resume. The admission controller will now invalidate backups using ephemeral volumes unless the defaultRecoveryMethod is set to either purge or none.

*https://jira.issues.couchbase.com/browse/K8S-3889/[K8S-3889]*::

Inplace upgrades are not supported prior to Couchbase Server Versions 7.2.x due to a required change in the startup files required by Couchbase Server. 





